### ISSUE TITLE
Extension not working at all: No context menu, settings, or omnibox support showing

### ISSUE THREAD

**Issue by jkupczak** [richardscarrott/snippets#31]
Not sure what's going on. I've installed the extension on two different Google Chrome profiles. The Snippets extension icon appears in the toolbar and it's light gray. Right-clicking on it shows an "Options" link that is grayed out and unclickable. Snippets doesn't show up in the right-click context menu on any page. And typing 's' and `tab` in the omnibox starts a search on Stackoverflow instead.

This is on Chrome 67.0.3396.87.

**Comment by richardscarrott** [comment]
@jkupczak I've got it installed and working on the exact same version of Chrome `67.0.3396.87` and many of my colleagues have it installed without a problem. Can you confirm you're running the latest version of Snippets, `0.2.7`?

It sounds like it's failing to even bootstrap itself but it's hard to say why. Could you inspect the background page and see if there are any errors in the console:

1) Go to `chrome://extensions`
2) Click `Details` on the Snippets card
3) Toggle `developer mode` in the top right
4) Under `inspect views` click `background page`

If there are any errors please share them here.

It might also be worth clearing down your local storage by running `chrome.storage.local.clear()` in the background page console (it'll only clear down storage for the Snippets extension).

Additionally, have you tried running the extension with all other extensions disabled (do you have a stackoverflow extension?) as it could potentially be a conflict with another extension?

**Comment by jkupczak** [comment]
Well this is embarrassing. I was using this extension with the exact same name:

https://chrome.google.com/webstore/detail/snippets/fakjeijchchmicjllnabpdkclfkpbiag

This isn't the right repository. Sorry!
